import 'package:flutter/material.dart';

import '../foundations/inter_commerce_color_primitives.dart';

/// Material [ColorScheme] mapping of the InterCommerce palette.
abstract final class InterCommerceColorSchemes {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(InterCommerceColorPrimitives.ink),
    onPrimary: Color(InterCommerceColorPrimitives.bone),
    primaryContainer: Color(InterCommerceColorPrimitives.linen),
    onPrimaryContainer: Color(InterCommerceColorPrimitives.ink),
    secondary: Color(InterCommerceColorPrimitives.earth),
    onSecondary: Color(InterCommerceColorPrimitives.bone),
    secondaryContainer: Color(InterCommerceColorPrimitives.parchment),
    onSecondaryContainer: Color(InterCommerceColorPrimitives.earthDark),
    tertiary: Color(InterCommerceColorPrimitives.roseGold),
    onTertiary: Color(InterCommerceColorPrimitives.ink),
    tertiaryContainer: Color(InterCommerceColorPrimitives.shell),
    onTertiaryContainer: Color(InterCommerceColorPrimitives.roseGoldDark),
    error: Color(InterCommerceColorPrimitives.bordeaux),
    onError: Color(InterCommerceColorPrimitives.bone),
    errorContainer: Color(InterCommerceColorPrimitives.bordeauxLight),
    onErrorContainer: Color(InterCommerceColorPrimitives.bordeaux),
    surface: Color(InterCommerceColorPrimitives.bone),
    onSurface: Color(InterCommerceColorPrimitives.ink),
    surfaceContainerLowest: Color(InterCommerceColorPrimitives.pureWhite),
    surfaceContainerLow: Color(InterCommerceColorPrimitives.linen),
    surfaceContainer: Color(InterCommerceColorPrimitives.parchment),
    surfaceContainerHigh: Color(InterCommerceColorPrimitives.shell),
    surfaceContainerHighest: Color(InterCommerceColorPrimitives.taupeMist),
    onSurfaceVariant: Color(InterCommerceColorPrimitives.ash),
    outline: Color(InterCommerceColorPrimitives.shell),
    outlineVariant: Color(InterCommerceColorPrimitives.taupeMist),
    inverseSurface: Color(InterCommerceColorPrimitives.espresso),
    onInverseSurface: Color(InterCommerceColorPrimitives.bone),
    inversePrimary: Color(InterCommerceColorPrimitives.stone),
    shadow: Color(InterCommerceColorPrimitives.pureBlack),
    scrim: Color(InterCommerceColorPrimitives.pureBlack),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(InterCommerceColorPrimitives.bone),
    onPrimary: Color(InterCommerceColorPrimitives.ink),
    primaryContainer: Color(InterCommerceColorPrimitives.inkSurfaceRaised),
    onPrimaryContainer: Color(InterCommerceColorPrimitives.linen),
    secondary: Color(InterCommerceColorPrimitives.earthLight),
    onSecondary: Color(InterCommerceColorPrimitives.espresso),
    secondaryContainer: Color(InterCommerceColorPrimitives.earthDark),
    onSecondaryContainer: Color(InterCommerceColorPrimitives.linen),
    tertiary: Color(InterCommerceColorPrimitives.roseGoldLight),
    onTertiary: Color(InterCommerceColorPrimitives.espresso),
    tertiaryContainer: Color(InterCommerceColorPrimitives.roseGoldDark),
    onTertiaryContainer: Color(InterCommerceColorPrimitives.linen),
    error: Color(InterCommerceColorPrimitives.bordeauxDark),
    onError: Color(InterCommerceColorPrimitives.espresso),
    errorContainer: Color(InterCommerceColorPrimitives.bordeaux),
    onErrorContainer: Color(InterCommerceColorPrimitives.bordeauxLight),
    surface: Color(InterCommerceColorPrimitives.inkSurface),
    onSurface: Color(InterCommerceColorPrimitives.linen),
    surfaceContainerLowest: Color(InterCommerceColorPrimitives.midnight),
    surfaceContainerLow: Color(InterCommerceColorPrimitives.inkSurfaceRaised),
    surfaceContainer: Color(InterCommerceColorPrimitives.inkSurfaceOverlay),
    surfaceContainerHigh: Color(InterCommerceColorPrimitives.charcoal),
    surfaceContainerHighest: Color(InterCommerceColorPrimitives.slate),
    onSurfaceVariant: Color(InterCommerceColorPrimitives.stone),
    outline: Color(InterCommerceColorPrimitives.inkBorder),
    outlineVariant: Color(InterCommerceColorPrimitives.charcoal),
    inverseSurface: Color(InterCommerceColorPrimitives.linen),
    onInverseSurface: Color(InterCommerceColorPrimitives.espresso),
    inversePrimary: Color(InterCommerceColorPrimitives.earthDark),
    shadow: Color(InterCommerceColorPrimitives.pureBlack),
    scrim: Color(InterCommerceColorPrimitives.pureBlack),
  );
}
